- index.html
> chore: add index.html

- .github/workflows/markdown.links.config.json
> ci: remove ignore pattern from markdown link check

- netlify.toml
Enable website preview with netlify.
> docs: enable website preview with netlify

- docs/book/src/SUMMARY.md
- docs/book/src/faq.md
- docs/book/src/installation/self-managed-clusters/oidc-issuer.md
- docs/book/src/topics/language-specific-examples/azure-identity-sdk.md
Adding FAQ page and minimum versions for azure-identity sdks.
> docs: add FAQ page and minimum versions for azure-identity sdks

- docs/book/src/faq.md
> docs: clarify pod identity v2 in faq

- manifest_staging/charts/workload-identity-webhook/templates/azure-wi-webhook-controller-manager-deployment.yaml
- third_party/open-policy-agent/gatekeeper/helmify/kustomize-for-helm.yaml
This PR adds the tolerations specified by users in the helm chart values to the webhook controller deployment. 
**Is this a deployment yaml update?**
Yes, updated the yaml.
**Are you making changes to the Helm chart?**
No added the changes to the helm chart generator.
> fix: Add tolerations to controller manager deployment.

- pkg/webhook/webhook.go
- pkg/webhook/webhook_test.go
- Resolves issue when pods using default service account in the namespace don't have the service account name set in the `PodSpec`.
fixes #441 
> fix: use default service account when service account name is empty

- pkg/cmd/serviceaccount/delete.go
- pkg/cmd/serviceaccount/phases/workflow/runner.go
- pkg/cmd/serviceaccount/phases/workflow/runner_test.go
> feat: optimize azwi serviceaccount delete

- scripts/create-aks-cluster.sh
> ci: pin aks-preview version to `0.5.87`

- config/manager/manager.yaml
- manifest_staging/charts/workload-identity-webhook/templates/azure-wi-webhook-controller-manager-deployment.yaml
- manifest_staging/deploy/azure-wi-webhook.yaml
Signed-off-by: Sertac Ozercan <sozercan@gmail.com>
Fixes #507 
> feat: add pod security admission support

- examples/msal-go/main.go
Make it easy to test in sovereign clouds
> chore: Load keyvault url from environment variable in example

- examples/msal-net/akvdotnet/Program.cs
- examples/msal-python/main.py
Follow up #563
Use full keyvault url in example.
> chore: Update KEYVAULT_URL in dotnet and python examples

- docs/book/src/topics/language-specific-examples/azure-identity-sdk.md
Update to non-beta Identity SDKs
/hold for .net confirmation
> docs: update to non-beta Azure Identity SDKs

- docs/book/src/topics/language-specific-examples/azure-identity-sdk.md
- examples/azure-identity/python/Dockerfile
- examples/azure-identity/python/Makefile
- examples/azure-identity/python/main.py
- examples/azure-identity/python/requirements.txt
- examples/msal-python/main.py
part of https://github.com/Azure/azure-workload-identity/issues/187
> feat: add azure-identity python example

- docs/book/src/troubleshooting.md
- Add troubleshooting guide for `AADSTS90061`
fixes https://github.com/Azure/azure-workload-identity/issues/605
> docs: add troubleshooting guide for AADSTS90061

- docs/book/src/quick-start.md
> docs: update tenant id step in quick start

- docs/book/src/quick-start.md
> docs: fix variable name in quick start

- docs/book/src/known-issues.md
> docs: fix header level in known-issues.md

- docs/book/src/topics/language-specific-examples/azure-identity-sdk.md
> docs: update go sdk ref link

- .github/workflows/azwi-e2e.yaml
> ci: changed Azure cli install to an upgrade

- scripts/create-aks-cluster.sh
> ci: update kubernetes version to v1.24 for aks 

- .github/workflows/azwi-e2e.yaml
> release: update manifest and helm charts for v1.0.0-alpha.0 (part 3)

- .github/workflows/codecov.yaml
- codecov.yml
> ci: add codecov.yml

- .github/workflows/azwi-build.yaml
- .github/workflows/azwi-e2e.yaml
- .github/workflows/codecov.yaml
- .github/workflows/create-release-pull-request.yaml
- .github/workflows/create-release.yaml
- .golangci.yml
- docker/proxy.Dockerfile
- docker/webhook.Dockerfile
- docs/book/src/development.md
- examples/azure-identity/go/Dockerfile
- examples/azure-identity/go/windows.Dockerfile
- examples/msal-go/Dockerfile
- examples/msal-go/windows.Dockerfile
> chore: update to go 1.20

- .pipelines/nightly.yaml
- .pipelines/pr.yaml
- switch to using mariner pool for PR and nightly jobs
> ci: switch to using mariner pool

- docker/proxy-init.Dockerfile
- use distroless-iptables for proxy-init
fixes #564
> feat: use distroless-iptables for proxy-init

- CODEOWNERS
> ci: add @enj to CODEOWNERS

- docs/book/src/troubleshooting.md
adds AADSTS90061 troubleshooting documentation for managed AKS clusters
- [n/A] added unit tests and e2e tests (if applicable).
> docs: add AADSTS90061 troubleshooting for managed AKS

- .github/dependabot.yml
- change dependabot schedule interval to weekly
> ci: change dependabot schedule interval to weekly

- docker/proxy-init.Dockerfile
- update distroless-iptables to v0.5.1
> chore: update distroless-iptables to v0.5.1

- .pipelines/nightly.yaml
- .pipelines/pr.yaml
- overwrite pool images using demands
> ci: overwrite pool images using demands

- .github/workflows/azwi-build.yaml
- .github/workflows/azwi-e2e.yaml
- update macos runner to macos-13
- `macos-11` runner has been removed.
> ci: update macos runner to macos-13

- docker/proxy-init.Dockerfile
- update distroless-iptables to `v0.6.1`
> chore: update distroless-iptables to v0.6.1

- .github/workflows/azwi-build.yaml
- .github/workflows/azwi-e2e.yaml
- .github/workflows/codecov.yaml
- .github/workflows/create-release-pull-request.yaml
- .github/workflows/create-release.yaml
- .github/workflows/scan-vulns.yaml
- .golangci.yml
- Makefile
- docker/proxy-init.Dockerfile
- docker/proxy.Dockerfile
- docker/webhook.Dockerfile
- examples/msal-go/Dockerfile
- go.mod
- pkg/cmd/podidentity/detect.go
- pkg/webhook/consts.go
- pkg/webhook/webhook.go
- test/e2e/go.mod
- update to go 1.23
- update distroless-iptables to `v0.6.3`
- update golangci-lint to `v1.61.0`
> chore: update to go 1.23

- .github/workflows/scan-vulns.yaml
- docker/proxy-init.Dockerfile
fixes https://github.com/Azure/azure-workload-identity/issues/1591
> chore: update distroless-iptables to v0.7.4
