.github/workflows/azwi-e2e.yaml
README.md

- `pull_request_target` is required for access to secrets from fork: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request_target
- fix broken links in docs with change to `/docs` in the url

chore: use `pull_request_target` and fix broken doc links

---

scripts/ci-e2e.sh

test: use official charts repo for helm upgrade tests

---

.github/workflows/azwi-e2e.yaml

Follow-up PR for #318. We need to check out the pull request head because pull_request_target checks out the main branch by default.

ci: checkout pull request head when running actions

---

pkg/cmd/serviceaccount/phases/create/federatedidentitycredential.go
pkg/cmd/serviceaccount/phases/create/federatedidentitycredential_test.go

Signed-off-by: GitHub <noreply@github.com>
Fixes #290. This PR will allow `azwi` to append new federated identity credential to a list of existing one.

fix: generate federated identity credential name based on service account

---

.github/dependabot.yml
examples/msal-node/package-lock.json

Addresses https://github.com/Azure/azure-workload-identity/security/dependabot/examples/msal-node/package-lock.json/follow-redirects/open.

security: update follow-redirects to 1.14.7

---

.github/dependabot.yml

ref: https://github.blog/changelog/2021-05-21-dependabot-version-updates-can-now-ignore-major-minor-patch-releases/

ci: update dependabot freq to weekly and pin to patch for go.mod

---

.github/dependabot.yml

The format requires `semver-*` prefix for version updates.

ci: add version-update semver-* prefix

---

.github/dependabot.yml

```bash
The property '#/updates/0/ignore/0/update-types/0' value "version-update: semver-major" did not match one of the following values: version-update:semver-major, version-update:semver-minor, version-update:semver-patch
The property '#/updates/0/ignore/0/update-types/1' value "version-update: semver-minor" did not match one of the following values: version-update:semver-major, version-update:semver-minor, version-update:semver-patch
```
It doesn't like the extra space in the config. Validated this on my fork: https://github.com/aramase/azure-workload-identity/runs/4900589418
Does this change contain code from or …

ci: fix dependabot update-types

---

docs/book/src/troubleshooting.md

docs: troubleshooting on incorrect token issuer

---

docker/proxy-init.Dockerfile

```bash
e2e/proxy-init:test-linux-amd64 (debian 11.0)
Total: 2 (MEDIUM: 2, HIGH: 0, CRITICAL: 0)
+----------+------------------+----------+-------------------+------------------+--------------------------------------+
| LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION   |                TITLE                 |
+----------+------------------+----------+-------------------+------------------+--------------------------------------+
| bsdutils | CVE-2021-3995    | MEDIUM   | 2.36.1-8          | 2.36.1-8+deb11u1 | util-linux: Unauthorized unmount     |
|          |                  |          |                   |                  | of FUSE …
```

security: fix CVE-2021-3995, CVE-2021-3996

---

docs/book/src/development.md
docs/book/src/installation/azwi.md
docs/book/src/topics/self-managed-clusters/service-account-key-rotation.md

Fixes #320. Removing `go install` step for azwi and advising users to download the tarball from our latest GitHub releases.

docs: remove `go install` step for azwi

---

.pipelines/templates/scan-images.yaml

ref: https://github.com/aquasecurity/trivy/discussions/1515

chore: migrate from `trivy` to `trivy image`

---

pkg/cloud/graph.go
pkg/cmd/serviceaccount/root.go

Fixes #352.
We should always check for graph errors from graph library responses before returning the graph objects. This PR also fixes `--debug` flag where it wasn't working when specificed.

fix: check for graph error from graph library response

---

docs/book/src/installation/mutating-admission-webhook.md

The webhook install URL responds with a 302. The user should follow the link.
Fixes a documentation issue.

fix(docs): webhook install follow redirect

---

docs/book/src/installation.md
docs/book/src/installation/mutating-admission-webhook.md
docs/book/src/known-issues.md
docs/book/src/quick-start.md
docs/book/src/topics/self-managed-clusters/service-account-key-rotation.md
pkg/webhook/consts.go
pkg/webhook/webhook_test.go
scripts/ci-e2e.sh
test/e2e/e2e.go
test/e2e/e2e_test.go
test/e2e/helpers.go

- Changes the mount path configured by webhook to `/var/run/secrets/azure/tokens` as `/var/run/secrets/tokens` could be used for other volume mounts. This change should be backward compatible as the users should rely on `AZURE_FEDERATED_TOKEN_FILE` environment variable which will have the correct value. 
fixes #357 

fix: change mount path to `/var/run/secrets/azure/tokens`

---

go.mod
go.sum
pkg/cmd/root.go

azwi can not auth with GKE clusters, see #362.
Fixes #362 

fix: enable auth with GKE clusters

---

.github/workflows/create-release.yaml

Follow up for https://github.com/Azure/azure-workload-identity/pull/364. Increase the goreleaser build timeout to `3h`

release: update manifest and helm charts for v0.8.0 (revision)

---

scripts/ci-e2e.sh
test/e2e/e2e.go
test/e2e/e2e_test.go
test/e2e/helpers.go

`e2e.volume-mount-path-to-check` was added to support upgrade testing from `v0.7.0` to latest. `v0.8.0` is now released and we no longer need this flag. This will also fix the helm upgrade failures in the nightly runs: https://dev.azure.com/AzureContainerUpstream/Azure%20Workload%20Identity/_build/results?buildId=37028&view=results

test: remove volume-mount-path-to-check e2e flag

---

.github/workflows/azwi-e2e.yaml

Uses `pull_request` instead of `pull_request_target` to prevent malicious commits.

ci: use pull_request instead of pull_request_target for Actions

---

.github/dependabot.yml

ci: use chore prefix for dependabot updates

---

.github/workflows/azwi-build.yaml
.github/workflows/azwi-e2e.yaml

`ACTIONS_ID_TOKEN_REQUEST_URL` and `ACTIONS_ID_TOKEN_REQUEST_TOKEN` environment variables are not available to forks even with `id-token` permission set to true. As part of this PR, we're splitting the existing azwi CI workflow:
1. Workflow to build azwi that runs periodically and as part of every PR.
2. E2E to create an app, add fic that runs periodically and after merge to main or release branches. 

ci: split azwi test workflow for e2e and build

---

pkg/cloud/azureclient.go

Do not specify tenant id when creating credential via Azure CLI. Instead, we should rely on Azure CLI to figure the tenant that the user has logged into.
Fixes #387

fix: do not specify tenant id when creating credential via Azure CLI

---

.pipelines/nightly.yaml
.pipelines/pr.yaml
.pipelines/templates/upgrade.yaml
scripts/ci-e2e.sh

Switching staging registry from using upstreamk8sci to upstream. 

chore: switch to upstream acr

---

docker/proxy.Dockerfile
init/init-iptables.sh
pkg/proxy/proxy.go
pkg/proxy/proxy_test.go

- Updates iptables rules to skip redirecting proxy traffic back to itself
- Updates user in `Dockerfile` for proxy 

fix: update proxy-init iptables rule to prevent forwarding loop

---

.pipelines/templates/scan-images.yaml
docker/proxy-init.Dockerfile

- Fixes the following CVEs:
- CVE-2021-33574
- CVE-2022-23218 
- CVE-2022-23219
- CVE-2021-3997
- Bumps default trivy version to 0.24.4
- Upgrades base image to bullseye-1.2.0

security: fix multiple cves

---

docker/proxy-init.Dockerfile

```bash
e2e/proxy-init:test-linux-amd64 (debian 11.1)
Total: 1 (MEDIUM: 0, HIGH: 1, CRITICAL: 0)
+---------+------------------+----------+-------------------+-------------------------+---------------------------------------+
| LIBRARY | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |      FIXED VERSION      |                 TITLE                 |
+---------+------------------+----------+-------------------+-------------------------+---------------------------------------+
| zlib1g  | CVE-2018-25032   | HIGH     | 1:1.2.11.dfsg-2   | 1:1.2.11.dfsg-2+deb11u1 | zlib: A flaw in zlib-1.2.11           |
|         |                  |          |                   | …
```

security: fix CVE-2018-25032

---

docker/proxy-init.Dockerfile

chore: upgrade to debian-iptables:bullseye-v1.3.0

---

.pipelines/pr.yaml

ci: exclude .github path in tests

---

pkg/cmd/root.go
pkg/cmd/serviceaccount/phases/create/serviceaccount_test.go
pkg/kuberneteshelper/serviceaccount.go
pkg/kuberneteshelper/serviceaccount_test.go
pkg/webhook/consts.go
pkg/webhook/webhook.go
pkg/webhook/webhook_test.go
test/e2e/proxy_test.go
test/e2e/token_exchange.go
test/e2e/webhook.go

chore: change variable name from pod to workload identity

---

.pipelines/templates/upgrade.yaml

test: check AKS agentpool provisioning state before upgrading

---

docker/proxy-init.Dockerfile

```bash
e2e/proxy-init:test-linux-amd64 (debian 11.3)
Total: 2 (MEDIUM: 0, HIGH: 2, CRITICAL: 0)
+----------+------------------+----------+-------------------+-------------------+--------------------------------------+
| LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |   FIXED VERSION   |                TITLE                 |
+----------+------------------+----------+-------------------+-------------------+--------------------------------------+
| gzip     | CVE-2022-1271    | HIGH     | 1.10-4            | 1.10-4+deb11u1    | gzip: arbitrary-file-write           |
|          |                  |          |                   |                   | …
```

security: fix CVE-2022-1271

---

.golangci.yml

follow-up to https://github.com/Azure/azure-workload-identity/pull/429. 
some of the linters don't work correctly with 1.18 (xref: https://github.com/golangci/golangci-lint/issues/2649). Pinning this to 1.17 as we are not using generics.
Running `make lint` will show the list of skipped linters with `v1.45.2` (ref: [CI run](https://dev.azure.com/AzureContainerUpstream/Azure%20Workload%20Identity/_build/results?buildId=42854&view=logs&jobId=3a559e2a-952e-58d2-b8db-2e604a9266d7&j=3a559e2a-952e-58d2-b8db-2e604a9266d7&t=0dc7cd25-c0cc-5e9c-2964-e6eb48aa3daf)):
```bash
level=warning msg="[linters context] gosimple is disabled because of go1.18. You can track the evolution of the go1.18 support by following the …
```

chore: use go 1.17 for golangci-lint

---

examples/msal-python/Dockerfile

Updating the image to use Debian 11.
When running the quick-start Python example the following error occurs.
```
$ kubectl logs quick-start
Traceback (most recent call last):
File "/app/main.py", line 4, in <module>
from azure.keyvault.secrets import SecretClient
ModuleNotFoundError: No module named 'azure'
```
The build base image is not the same as the runtime one. Build is buster 10 and runtime is bullseye 11.
Debian has already been bumped in the [original reference code](https://github.com/GoogleContainerTools/distroless/commit/d4d6e705d769eb21bb2a020bb096d0bc624e1d57), and that incidentally fixes the issue as well.
**Issue Fixed**: #436
Does this change contain code from or inspired by …

fix: use debian11 in Dockerfile build image

---

docker/proxy-init.Dockerfile

```bash
e2e/proxy-init:test-linux-amd64 (debian 11.3)
Total: 1 (MEDIUM: 0, HIGH: 0, CRITICAL: 1)
+-----------+------------------+----------+-------------------+------------------+--------------------------------------+
|  LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION   |                TITLE                 |
+-----------+------------------+----------+-------------------+------------------+--------------------------------------+
| libssl1.1 | CVE-2022-1292    | CRITICAL | 1.1.1n-0+deb11u1  | 1.1.1n-0+deb11u2 | openssl: c_rehash script             |
|           |                  |          |                   |                  | …
```

security: fix CVE-2022-1292

---

docker/proxy-init.Dockerfile

```bash
e2e/proxy-init:test-linux-amd64 (debian 11.3)
Total: 1 (MEDIUM: 1, HIGH: 0, CRITICAL: 0)
+---------+------------------+----------+-------------------+---------------+--------------------------------------+
| LIBRARY | VULNERABILITY ID | SEVERITY | INSTALLED VERSION | FIXED VERSION |                TITLE                 |
+---------+------------------+----------+-------------------+---------------+--------------------------------------+
| dpkg    | CVE-2022-1664    | MEDIUM   | 1.20.9            | 1.20.10       | Dpkg::Source::Archive in             |
|         |                  |          |                   |               | dpkg, the Debian package …
```

security: fix CVE-2022-1664

---

manifest_staging/charts/workload-identity-webhook/templates/azure-wi-webhook-controller-manager-deployment.yaml
third_party/open-policy-agent/gatekeeper/helmify/kustomize-for-helm.yaml

- Adds affinity to deployment in helm charts
fixes #456 

fix: add affinity to deployment in helm charts

---

.github/workflows/azwi-e2e.yaml
docs/book/src/known-issues.md
docs/book/src/quick-start.md
docs/book/src/topics/federated-identity-credential.md

`azwi_e2e` has been failing because the `APPLICATION_OBJECT_ID` is empty: https://github.com/Azure/azure-workload-identity/runs/6716352232?check_suite_focus=true. The application object id is now in `id` parameter and there is no
`objectId` field in the 'az ad app show' response (xref: https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration#breaking-changes). This change will fix the azwi e2e CI failure. Also, updating all the references in the docs.

fix: use `id` instead of `objectId` for app object id

---

docker/proxy-init.Dockerfile

Update debian-iptables to bullseye-v1.4.0

chore: update debian-iptables to bullseye-v1.4.0

---

docs/book/src/faq.md

docs: many-to-one relationship and fic delay

---

pkg/webhook/webhook.go
pkg/webhook/webhook_test.go
scripts/ci-e2e.sh
test/e2e/webhook.go

-  Allow setting `azure.workload.identity/use` in annotations in addition to labels
fixes #473 
- I'm thinking of updating the docs after `v0.11.0` release

feat: allow setting `azure.workload.identity/use` in annotations

---

docs/book/src/topics/federated-identity-credential.md

Looks like a copy/paste error.

fix: --aad-appliction-name arg listed twice

---

pkg/proxy/proxy.go

- Logging the user agent at start in proxy to know which version is currently running

chore: add user agent to start log in proxy

---

Makefile
scripts/ci-e2e.sh
test/e2e/e2e.go
test/e2e/e2e_test.go
test/e2e/proxy_test.go

test: remove GINKGO_SKIP in upgrade tests

---

docker/proxy-init.Dockerfile

- update debian-iptables to bullseye-v1.5.0

chore: update debian-iptables to bullseye-v1.5.0

---

docker/proxy-init.Dockerfile
docker/proxy.Dockerfile
docker/webhook.Dockerfile
examples/msal-go/Dockerfile
examples/msal-go/windows.Dockerfile
examples/msal-java/Dockerfile
examples/msal-node/Dockerfile
examples/msal-python/Dockerfile

This PR migrates all Dockerhub images to MCR and parameterizes non-Dockerfile images.
Fixes #482. 

refactor: migrate golang to MCR and parameterize non-Dockerhub images

---

cmd/proxy/main.go
pkg/cmd/podidentity/detect.go
pkg/cmd/podidentity/detect_test.go
pkg/proxy/probe.go
pkg/proxy/probe_test.go
pkg/proxy/proxy.go
pkg/proxy/proxy_test.go
pkg/webhook/webhook.go
pkg/webhook/webhook_test.go
scripts/ci-e2e.sh
test/e2e/proxy_test.go

- Adds a new `--probe` option to the proxy binary
- When proxy is run with `--probe`, it'll run a readyz probe to check if the proxy is running and ready to serve requests.
fixes #486 

feat: add proxy --probe and enable lifecycle postStart hook

---

CODEOWNERS

Thank you for all the contributions, Ernest!!!
I wish there was a way to add emeritus to the codeowners file.

ci: remove @chewong from CODEOWNERS

---

.github/workflows/azwi-e2e.yaml
docs/book/src/topics/azwi/serviceaccount-create.md
docs/book/src/topics/azwi/serviceaccount-delete.md

- Updates the `SERVICE_ACCOUNT_ISSUER` for azwi e2e
- https://azwi.blob.core.windows.net/oidc-test/.well-known/openid-configuration

ci: update `SERVICE_ACCOUNT_ISSUER` in azwi e2e

---

.pipelines/pr.yaml

The AKS upgrade tests take 34m to complete. Upgrade tests are run as part of nightly CI, so removing it from PR gate to improve merge time.
https://github.com/Azure/azure-workload-identity/blob/8644a217f09902fa1ac63e05cf04d9a3f3f1ebc3/.pipelines/nightly.yaml#L105-L122

ci: remove `upgrade_aks_linux` tests in pr.yaml

---

examples/msal-java/pom.xml
examples/msal-java/src/main/java/com/example/msal/java/CustomTokenCredential.java

The current msal-java example exhibits very poor practice in the use of reactive streams.  When a method like `TokenCredential.getToken` returns a `Mono` the caller should expect that the calling thread will not block, and that any potentially long running operations will occur when the resulting `Mono` is _subscribed_, rather than blocking the caller.  Currently `getToken` includes two blocking operations, first the read of the token file from disk and second the call to `CompletableFuture.join()` on the future returned by `ConfidentialClientApplication.acquireToken`.
This PR moves the file read into the `CustomTokenCredential` constructor (which is not a reactive call), and makes `getToken` properly non-blocking.
**Please answer the following …

refactor: Improve Reactor API usage in Java example

---

manifest_staging/charts/workload-identity-webhook/README.md
manifest_staging/charts/workload-identity-webhook/templates/azure-wi-webhook-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml
manifest_staging/charts/workload-identity-webhook/values.yaml
third_party/open-policy-agent/gatekeeper/helmify/kustomize-for-helm.yaml
third_party/open-policy-agent/gatekeeper/helmify/replacements.go
third_party/open-policy-agent/gatekeeper/helmify/static/README.md
third_party/open-policy-agent/gatekeeper/helmify/static/values.yaml

- Make mwh `failurePolicy` configurable in helm charts
fixes https://github.com/Azure/azure-workload-identity/issues/516

feat: make mwh failurePolicy configurable in helm charts

---

config/manager/manager.yaml
manifest_staging/charts/workload-identity-webhook/README.md
manifest_staging/charts/workload-identity-webhook/templates/azure-wi-webhook-controller-manager-deployment.yaml
manifest_staging/charts/workload-identity-webhook/values.yaml
manifest_staging/deploy/azure-wi-webhook.yaml
third_party/open-policy-agent/gatekeeper/helmify/kustomize-for-helm.yaml
third_party/open-policy-agent/gatekeeper/helmify/replacements.go
third_party/open-policy-agent/gatekeeper/helmify/static/README.md
third_party/open-policy-agent/gatekeeper/helmify/static/values.yaml

- Make priority class name configurable in helm chart
- Set default priority class name to `system-cluster-critical` for the webhook
fixes https://github.com/Azure/azure-workload-identity/issues/519

feat: make priority class name configurable in helm charts

---

docs/book/src/quick-start.md

docs: update quick-start to use azure cli for federated credentials

---

docs/book/src/known-issues.md

Added known issue as discussed here: https://github.com/Azure/azure-workload-identity/issues/525

docs: add AKS admission enforcer to known issues

---

manifest_staging/charts/workload-identity-webhook/README.md
manifest_staging/charts/workload-identity-webhook/templates/azure-wi-webhook-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml
manifest_staging/charts/workload-identity-webhook/values.yaml
third_party/open-policy-agent/gatekeeper/helmify/kustomize-for-helm.yaml
third_party/open-policy-agent/gatekeeper/helmify/replacements.go
third_party/open-policy-agent/gatekeeper/helmify/static/README.md
third_party/open-policy-agent/gatekeeper/helmify/static/values.yaml

ref: https://azure.github.io/azure-workload-identity/docs/known-issues.html#environment-variables-not-injected-into-pods-deployed-in-the-kube-system-namespace-in-an-aks-cluster
resolves #525 

feat: allow setting mwh annotations in helm charts

---

scripts/create-aks-cluster.sh

- update default aks cluster version to 1.23 as 1.21 is EOL
- fixes CI failures https://dev.azure.com/AzureContainerUpstream/Azure%20Workload%20Identity/_build/results?buildId=54608&view=logs&jobId=3a3ff92c-2ab0-5cd5-ecad-e283f5e1d802

test: update default aks cluster version to 1.23

---

docker/proxy-init.Dockerfile

- update debian-iptables to bullseye-v1.5.1

chore: update debian-iptables to bullseye-v1.5.1

---

docker/proxy-init.Dockerfile

ref: https://dev.azure.com/AzureContainerUpstream/Azure%20Workload%20Identity/_build/results?buildId=54815&view=logs&jobId=50e5c204-a982-5a63-4824-cf22f1b24a4e&j=50e5c204-a982-5a63-4824-cf22f1b24a4e&t=94cd4644-8683-57bb-f7f8-715cbe70e34e

security: fix CVE-2022-37434

---

config/default/kustomization.yaml
config/pdb/kustomization.yaml
config/pdb/pdb.yaml
manifest_staging/charts/workload-identity-webhook/templates/azure-wi-webhook-controller-manager-poddisruptionbudget.yaml
manifest_staging/deploy/azure-wi-webhook.yaml

- Add pod disruption budget for webhook

feat: add pod disruption budget for webhook

---

.goreleaser.yml

- Temporarily disable `darwin` builds for `azwi` as build is timing out https://github.com/Azure/azure-workload-identity/actions/runs/2959224095/attempts/1. We can re enable this debugging in the next release. 

release: update manifest and helm charts for v0.13.0 (revision)

---

docs/book/src/quick-start.md

Update doc to use KEYVAULT_URL, so as to support sovereign clouds
Follow-up #561

docs: Use KEYVAULT_URL in quick start guide

---

docs/book/src/topics/language-specific-examples/azure-identity-sdk.md
examples/azure-identity/dotnet/Dockerfile
examples/azure-identity/dotnet/Makefile
examples/azure-identity/dotnet/Program.cs
examples/azure-identity/dotnet/akvdotnet.csproj

feat: add azure-identity .NET example

---

docs/book/src/topics/language-specific-examples/azure-identity-sdk.md
examples/azure-identity/java/Dockerfile
examples/azure-identity/java/Makefile
examples/azure-identity/java/pom.xml
examples/azure-identity/java/src/main/java/com/example/azureidentity/java/App.java

feat: add azure-identity java example

---

scripts/create-aks-cluster.sh

- Pinning to 1.22 with upgrade to 1.23 because windows agent pool is not supported for k8s version above 1.24.0
```bash
ERROR: (AgentPoolK8sVersionNotSupported) windows agentpool is not supported for k8s version above 1.24.0
```
fixes failures in nightly CI: https://dev.azure.com/AzureContainerUpstream/Azure%20Workload%20Identity/_build/results?buildId=59184&view=logs&jobId=7939843a-c18e-59f2-9e98-8c01c1bb1590&j=7939843a-c18e-59f2-9e98-8c01c1bb1590&t=c8e72aab-643b-5650-d9f9-6570bfa55e8f …

test: pin default aks cluster version to 1.22

---

docs/book/src/quick-start.md

This PR fixes the instructions in step 4 of the quick start guide when using user-assigned managed identities. Specifically, the change is to use the managed identity's `principalId` instead of `clientId` for the `--object-id` parameter when creating the Key Vault security policy.
The quick start guide didn't work when using user-assigned managed identities. Specifically, I saw 
```console
{"error":{"code":"Forbidden","message":"The user, group or application 'appid=REDACTED-CLIENT_ID;oid=REDACTED-PRINCIPAL_ID;iss=https://sts.windows.net/REDACTED/' does not have secrets 
get permission on key vault 'REDACTED;location=eastus'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287","innererror":{"code":"AccessDenied"}}}
```
**Is …

docs: update keyvault command for managed identity in quickstart

---

scripts/create-aks-cluster.sh

AKS issue with windows nodepool for 1.24 has been fixed: https://github.com/Azure/AKS/issues/3246, so we can reenable upgrade tests from 1.23 to 1.24.
fixes https://github.com/Azure/azure-workload-identity/issues/587

test: use kubernetes v1.23 for aks cluster

---

charts/artifacthub-repo.yml

- Adds artifacthub metadata file for `Verified Publisher` label (ref: https://artifacthub.io/docs/topics/repositories/#verified-publisher)
Package ref: https://artifacthub.io/packages/helm/azure-workload-identity/workload-identity-webhook

chore: add artifacthub metadata file

---

pkg/proxy/proxy.go

ref: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/747 For MSAL (v2.0 endpoint) asking an access token for a resource that accepts a v1.0 access token, Azure AD parses the desired audience from the requested scope by taking everything before the last slash and using it as the resource identifier. For example, if the scope is "https://vault.azure.net/.default", the resource identifier is "https://vault.azure.net". If the scope is "http://database.windows.net//.default", the resource identifier is "http://database.windows.net/".
Does this change contain code from or inspired by another …

fix: remove trim suffix from resource_id in proxy

---

.github/dependabot.yml

ci: add test/e2e to dependabot config

---

.github/workflows/create-release.yaml
.github/workflows/publish-images.yaml

xref: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

ci: update `set-output` to use `GITHUB_OUTPUT` in workflow

---

manifest_staging/charts/workload-identity-webhook/README.md
manifest_staging/charts/workload-identity-webhook/templates/_helpers.tpl
manifest_staging/charts/workload-identity-webhook/templates/azure-wi-webhook-controller-manager-deployment.yaml
manifest_staging/charts/workload-identity-webhook/values.yaml
third_party/open-policy-agent/gatekeeper/helmify/main.go
third_party/open-policy-agent/gatekeeper/helmify/static/README.md
third_party/open-policy-agent/gatekeeper/helmify/static/templates/_helpers.tpl
third_party/open-policy-agent/gatekeeper/helmify/static/values.yaml

- Adds support for configuring labels in the webhook pods.
fixes https://github.com/Azure/azure-workload-identity/issues/551

feat: add podLabels to helm charts

---

pkg/proxy/proxy.go

- [msal-go](https://github.com/AzureAD/microsoft-authentication-library-for-go) returns [AuthResult](https://pkg.go.dev/github.com/AzureAD/microsoft-authentication-library-for-go@v0.7.0/apps/internal/base#AuthResult) which doesn't contain the `expires_in` value. Computing that in the proxy based on current time and expires_on. This change is to make the response consistent with the IMDS response and also AAD response for token request.
This is the AAD response:
```json
{
"token_type": "Bearer",
"expires_in": 86399,
"ext_expires_in": 86399,
"access_token": "<token>"
}
```
xref: https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#successful-response-2 …

fix: set `expires_in` the proxy token response

---

pkg/proxy/proxy.go
pkg/proxy/proxy_test.go
test/e2e/proxy_test.go

If clientID not found in request in the `client_id` parameter, then we default to the `AZURE_CLIENT_ID` env var if present. This is to keep consistent with the current behavior in pod identity v1 where we default the client id to the one in `AzureIdentity` if clientID isn't provided as part of the token request.
fixes https://github.com/Azure/azure-workload-identity/issues/145

feat: Fallback to `AZURE_CLIENT_ID` env var if no `client_id` query param in token request

---

.pipelines/nightly.yaml
.pipelines/pr.yaml
README.md

- Remove Kubernetes version 1.22 from docs and CI since it has reached EOL

docs: remove kubernetes version 1.22 (EOL)

---

docs/book/src/installation/managed-clusters.md

The link to the Azure docs is semi-broken due to the change in the header name. It is also region specific instead of generalized, and uses the old docs subdomain instead of learn.
- Remove preview suffix
- Remove region-specific path
- Switch to new learn platform instead of docs

docs: Update link to AKS docs for OIDC Issuer

---

docs/book/src/development.md

- replace pmi with azwi in development doc _(pmi was reference to the old project name)_

docs: replace pmi with azwi in development doc

---

docs/book/src/faq.md

- Adds minimum required permissions for creating/deleting/updating federated identity credential with Azure AD Apps and user-assigned managed identity. 
fixes #548 

docs: add minimum required permissions for creating federated identity credential

---

docs/book/src/faq.md
docs/book/src/installation.md
docs/book/src/installation/mutating-admission-webhook.md
docs/book/src/known-issues.md

Add `` in few more docs to autogenerate table of contents

docs: add inline table of contents

---

config/webhook/manifests.yaml
manifest_staging/charts/workload-identity-webhook/templates/azure-wi-webhook-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml
manifest_staging/deploy/azure-wi-webhook.yaml
pkg/webhook/webhook.go

- If the pod is in terminating state, we return early in the handler as mutation/check doesn't apply to those.
#647 

fix: remove `UPDATE` operation from mutatingwebhookconfiguration

---

pkg/proxy/proxy.go
pkg/proxy/proxy_test.go

fix: use `HasSuffix` check for generating scope

---

.pipelines/nightly.yaml
.pipelines/pr.yaml
README.md

- enable tests with kubernetes v1.26

ci: enable tests with kubernetes v1.26

---

go.mod
go.sum
test/e2e/go.mod
test/e2e/go.sum

```bash
┌──────────────────┬────────────────┬──────────┬────────────────────────────────────┬───────────────┬──────────────────────────────────────────────────────────────┐
│     Library      │ Vulnerability  │ Severity │         Installed Version          │ Fixed Version │                            Title                             │
├──────────────────┼────────────────┼──────────┼────────────────────────────────────┼───────────────┼──────────────────────────────────────────────────────────────┤
│ golang.org/x/net │ CVE-2022-41717 │ MEDIUM   │ v0.0.0-20220906165146-f3363e06e74c │ 0.4.0         │ An attacker can cause excessive memory growth in a Go server │
│                  │                │          │ …
```

security: fix CVE-2022-41717

---

scripts/ci-e2e.sh

- remove mutate pod based on label tests from `GINKGO_SKIP`. The test will now be run pre-upgrade and post-upgrade.

test: remove mutate pod based on label tests from GINKGO_SKIP

---

docs/book/src/quick-start.md

Previous code will return `Unable to get object id from principal name.`
Using `--spn` only works after a period of time ~60s, using `--object-id` works immediately.

docs: Update quick start doc for user assigned identity

---

pkg/webhook/webhook.go
pkg/webhook/webhook_test.go

fix: explicitly set runAsNonRoot to false (#697)

---

pkg/webhook/webhook.go

For static pods, the pod name is not empty. For pods created as part of `Deployments`, `ReplicaSet`, etc, the name is empty and generate name exists.
```console
I0117 22:08:19.736489       1 webhook.go:114] handler "msg"="received pod mutation request pod.GetName()" "namespace"="default" "pod"="" "podName"="" "service-account"="wi"
I0117 22:08:19.736518       1 webhook.go:115] handler "msg"="received pod mutation request pod.GetGenerateName()" "namespace"="default" "pod"="" "podName"="nginx-deployment-84d95667b8-" "service-account"="wi"
```
Actual log with this change
```console
I0117 23:13:27.617001       1 webhook.go:142] handler "msg"="pod not labeled or service account not annotated, skipping mutation" …
```

fix: use generate name in logs if pod name is empty

---

Makefile

chore: pin buildx version to `0.10.6`

---

cmd/webhook/main.go
config/manager/manager.yaml
manifest_staging/charts/workload-identity-webhook/templates/azure-wi-webhook-controller-manager-deployment.yaml
manifest_staging/deploy/azure-wi-webhook.yaml
scripts/ci-e2e.sh

Block readiness on the mutating webhook being registered. We can't use `mgr.GetWebhookServer().StartedChecker()` yet, because that starts the webhook. But we also can't call `AddReadyzCheck` after `Manager.Start`. So we need a custom ready check that delegates to the real ready check after the cert has been injected and validator started.
fixes #709 
fixes #714 

feat: use cert ready checker for webhook readiness

---

pkg/cmd/podidentity/detect.go
pkg/cmd/podidentity/detect_test.go
pkg/cmd/serviceaccount/phases/create/serviceaccount_test.go
pkg/kuberneteshelper/serviceaccount.go
pkg/kuberneteshelper/serviceaccount_test.go
pkg/webhook/webhook.go
pkg/webhook/webhook_test.go
test/e2e/webhook.go

With the objectselector set in mwh, only pods that have the label `azure.workload.identity/use: "true"` will be sent to the webhook for mutation. We no longer need the check for pod/service account labeled.
fixes https://github.com/Azure/azure-workload-identity/issues/658

feat: remove pod/service account labeled check in webhook

---

.github/workflows/azwi-e2e.yaml

resolves `azwi-e2e` failures: https://github.com/Azure/azure-workload-identity/actions/runs/4050485121/jobs/6968544935 as `azwi` no longer annotates the service account.

test: remove sa label check in e2e

---

docs/book/src/faq.md

With this PR I'm simply adding the information I got from @aramase in this issue (https://github.com/Azure/azure-workload-identity/issues/731), related to the migration from `aad-pod-identity`.

docs: Add `aad-pod-identity` migration information

---

cmd/azwi/main.go
go.mod
go.sum
pkg/cloud/azureclient.go
pkg/cloud/graph.go
pkg/cloud/roleassignments.go
pkg/cloud/roledefinitions.go
pkg/cmd/jwks/root.go
pkg/cmd/podidentity/detect.go
pkg/cmd/podidentity/root.go
pkg/cmd/root.go
pkg/cmd/serviceaccount/auth/provider.go
pkg/cmd/serviceaccount/create.go
pkg/cmd/serviceaccount/create_test.go
pkg/cmd/serviceaccount/delete.go
pkg/cmd/serviceaccount/phases/create/aadapplication.go
pkg/cmd/serviceaccount/phases/create/federatedidentitycredential.go
pkg/cmd/serviceaccount/phases/create/roleassignment.go
pkg/cmd/serviceaccount/phases/create/serviceaccount.go
pkg/cmd/serviceaccount/phases/delete/aadapplication.go
pkg/cmd/serviceaccount/phases/delete/federatedidentitycredential.go
pkg/cmd/serviceaccount/phases/delete/roleassignment.go
pkg/cmd/serviceaccount/phases/delete/serviceaccount.go
pkg/cmd/serviceaccount/phases/workflow/runner.go
pkg/cmd/serviceaccount/root.go
test/e2e/go.mod
test/e2e/go.sum

Signed-off-by: Monis Khan <mok@microsoft.com>
Fixes #705
Example logs with `--debug`:
```
Wed, 01 Feb 2023 17:43:07 EST  auth/provider.go:191  No subscription provided, using selected subscription from Azure CLI  {"subscription-id": "ID_HERE"}
Wed, 01 Feb 2023 17:43:07 EST  cloud/azureclient.go:235  Resolving tenantID  {"subscriptionID": "ID_HERE"}
Wed, 01 Feb 2023 17:43:07 EST  serviceaccount/delete.go:115  --aad-application-name not specified, constructing name with service account namespace, name, and the hash of the issuer URL  {"warning": true}
Wed, 01 Feb 2023 17:43:07 EST  cloud/graph.go:96  Getting application  {"display name": "default-foo-T"}
Wed, 01 Feb 2023 17:43:07 EST  transport/round_trippers.go:466  curl -v -XGET  -H "User-Agent: azsdk-go-azidentity/v0.13.2 …
```

chore: complete migration to mlog and drop logrus

---

docs/book/src/known-issues.md
docs/book/src/quick-start.md
docs/book/src/topics/self-managed-clusters/service-account-key-rotation.md
docs/book/src/topics/service-account-labels-and-annotations.md
docs/book/src/troubleshooting.md

- Adds note about the required pod label for mutation
- Marks the service account label as required only for `< v1.0.0`. _This section will be removed post `v1.0.0` release._
- Updates troubleshooting guide for possible issue post upgrade to `v1.0.0`. This section will be linked to `Breaking Changes` in the release notes.

docs: update docs for v1.0.0-alpha.0 release

---

.github/workflows/create-release-pull-request.yaml

- update tag validation in `create_release_pull_request` workflow to allow alpha, beta and rc suffixes.

ci: update tag validation to allow alpha/beta/rc

---

.github/workflows/azwi-e2e.yaml

Skip prompt with `-y` arg. This should fix the e2e failures in `main` branch (ref: https://github.com/Azure/azure-workload-identity/actions/runs/4119079845/jobs/7112353016)

ci: add `-y` arg for az upgrade

---

.github/workflows/azwi-e2e.yaml

- add `--only-show-errors` in az upgrade to suppress warnings

ci: add `--only-show-errors` in az upgrade to suppress warnings

---

docs/book/src/faq.md

docs: add note about disconnected env in faq

---

scripts/ci-e2e.sh

- Install development versions of helm charts (e.g `v1.0.0-alpha.X`) as part of helm upgrade tests
- Update `poll_webhook_readiness` in test to check newly added webhook readiness

test: install devel releases with helm and update webhook poll_webhook_readiness

---

docker/proxy-init.Dockerfile

- update debian-iptables to bullseye-v1.5.2

chore: update debian-iptables to bullseye-v1.5.2

---

.pipelines/nightly.yaml
.pipelines/pr.yaml
README.md

- Remove Kubernetes version 1.23 from docs and CI since it has reached EOL
- Update Kubernetes versions to latest in CI for supported releases

docs: remove kubernetes version 1.23 (EOL)

---

cmd/proxy/main.go
pkg/proxy/proxy.go

- add graceful shutdown for proxy server

feat: add graceful shutdown for proxy server

---

config/rbac/role.yaml
manifest_staging/charts/workload-identity-webhook/templates/azure-wi-webhook-manager-role-clusterrole.yaml
manifest_staging/deploy/azure-wi-webhook.yaml
pkg/webhook/webhook.go

- Remove `CREATE`, `PATCH`, `UPDATE` for service accounts
- Remove `CREATE`, `PATCH`  and `DELETE` for mutating webhook configuration

fix: remove unnecessary rbac permissions for mwh

---

manifest_staging/charts/workload-identity-webhook/README.md
manifest_staging/charts/workload-identity-webhook/templates/azure-wi-webhook-controller-manager-deployment.yaml
manifest_staging/charts/workload-identity-webhook/values.yaml
third_party/open-policy-agent/gatekeeper/helmify/kustomize-for-helm.yaml
third_party/open-policy-agent/gatekeeper/helmify/replacements.go
third_party/open-policy-agent/gatekeeper/helmify/static/README.md
third_party/open-policy-agent/gatekeeper/helmify/static/values.yaml

- make pod annotations configurable in helm charts
fixes #789 

feat: make pod annotations configurable in helm charts

---

config/webhook/manifests.yaml
manifest_staging/charts/workload-identity-webhook/templates/azure-wi-webhook-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml
manifest_staging/deploy/azure-wi-webhook.yaml
pkg/webhook/webhook.go

- Sets `reinvocationPolicy: IfNeeded` for the workload identity mutating webhook.
fixes #787
fixes #791 
- Validated this with the [dapr](https://learn.microsoft.com/en-us/azure/aks/dapr) extension.

feat: set `reinvocationPolicy: IfNeeded` for webhook

---

docker/proxy-init.Dockerfile

- update debian-iptables to bullseye-v1.5.3

chore: update debian-iptables to bullseye-v1.5.3

---

docs/book/src/installation/managed-clusters.md

When reading the documentation to start using this tool, I noticed that the AKS OIDC documentation link was incorrect. Indeed, the OIDC section apparently was taken away from the original page, and now we have a specific page for it, that is used in this PR.
Please, let me know if you'd like me to change something in the PR.

docs: Update AKS OIDC Issuer link

---

.golangci.yml

xref: https://golangci-lint.run/usage/linters/#golint

ci: add local-prefixes goimports linter-settings

---

docker/proxy-init.Dockerfile

- update debian-iptables to bullseye-v1.5.4

chore: update debian-iptables to bullseye-v1.5.4

---

pkg/webhook/webhook.go
pkg/webhook/webhook_test.go

- explicitly set security capabilities for the inject `azwi-proxy` sidecar container

feat: set security capabilities for azwi-proxy

---

docker/proxy-init.Dockerfile

- update debian-iptables to bullseye-v1.5.5

chore: update debian-iptables to bullseye-v1.5.5

---

examples/azure-identity/dotnet/Makefile
examples/msal-go/Makefile
examples/msal-net/akvdotnet/Makefile

- Remove `1903`, `1909` and `2004` for windows builds (EOL)
- https://learn.microsoft.com/en-us/lifecycle/announcements/windows-10-1903-end-of-servicing
- https://learn.microsoft.com/en-us/lifecycle/announcements/windows-10-1909-end-of-servicing
- https://learn.microsoft.com/en-us/lifecycle/announcements/windows-10-version-2004-end-of-servicing

chore: remove windows version 1903, 1909 and 2004 (EOL)

---

.github/workflows/codeql.yaml

With the older versions of graph sdk, it took ~ 1h for the action to complete. With the recent upgrades to latest sdk, the action only takes 6-8 mins which is ok to be run.

ci: enable codeql for pull_request

---

.pipelines/nightly.yaml
.pipelines/pr.yaml

- enable tests with kubernetes v1.27 (nightly)

ci: enable tests with kubernetes v1.27 (nightly)

---

docs/book/src/faq.md
docs/book/src/quick-start.md

- Add a note about mapping multiple Kubernetes service account to single identity and multiple identities with single Kubernetes service account in FAQ. 
- Also add a reference note in quick start.

docs: add note about many:1 and 1:many in quick start

---

.goreleaser.yml

- reenable azwi darwin build as part of release
- It was disabled before because of the build times associated with the msgraph sdk. With the upgrade to latest sdk, the build time is reduced and we should be able to build all `goos`.

chore: reenable azwi darwin build as part of release

---

.pipelines/pr.yaml

- exclude examples folder from CI except for `msal-go` example as that is used for e2e

ci: exclude examples folder from trigger

---

.pipelines/pr.yaml

Adding all the files to `include` explicitly

ci: exclude examples folder from trigger (part 2)

---

go.mod
pkg/cloud/azureclient.go
pkg/cloud/errors.go
pkg/cloud/errors_test.go
pkg/cloud/graph.go
pkg/cloud/roleassignments.go
pkg/cmd/serviceaccount/phases/create/federatedidentitycredential.go
pkg/cmd/serviceaccount/phases/create/federatedidentitycredential_test.go
pkg/cmd/serviceaccount/phases/create/roleassignment.go
pkg/cmd/serviceaccount/phases/create/roleassignment_test.go
pkg/cmd/serviceaccount/phases/delete/federatedidentitycredential_test.go
pkg/cmd/serviceaccount/phases/delete/roleassignment_test.go

- Use `odataerrors.ODataError` for graph errors; contains the inner error and other details from additionalData that we were previously parsing because of sdk limitations.
- Use `*azcore.ResponseError` as part of switch to the new sdk for role assignments and role definitions client.
Validated it locally
```console
➜ ./bin/azwi sa create --service-account-name idsa --service-account-namespace oidc --aad-application-name graphtest01 --azure-role Reader --azure-scope "/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/aramasedev/providers/Microsoft.KeyVault/vaults/adevkv" --subscription-id <SUBSCRIPTION_ID> --auth-method cli --service-account-issuer-url https://kubernetes.svc.cluster.local
Thu, 04 May 2023 23:52:58 UTC  serviceaccount/create.go:175  --service-principal-name not specified, …
```

refactor: use odataerrors and azcore response error

---

docker/proxy-init.Dockerfile

- update distroless-iptables to v0.2.4

chore: update distroless-iptables to v0.2.4

---

go.mod
go.sum
pkg/cloud/graph.go
pkg/cmd/serviceaccount/create_test.go
pkg/cmd/serviceaccount/phases/create/aadapplication_test.go
pkg/cmd/serviceaccount/phases/create/federatedidentitycredential.go
pkg/cmd/serviceaccount/phases/create/federatedidentitycredential_test.go
pkg/cmd/serviceaccount/phases/create/roleassignment_test.go
pkg/cmd/serviceaccount/phases/delete/federatedidentitycredential_test.go

- chore: use `github.com/Azure/azure-sdk-for-go/sdk/azcore/to` instead of `autorest/to`

chore: use `github.com/Azure/azure-sdk-for-go/sdk/azcore/to` instead of `autorest/to`

---

docs/book/src/topics/federated-identity-credential.md

The documentation has MarkDown formatting errors. 
**Issue Fixed**: None

docs: fix markdown syntax in federated identity credentials doc

---

Makefile

The `storage.googleapis.com/kubernetes-release` URL is a hard coded path to a GCS bucket location. To allow redirecting and spreading the load across multiple hosting locations, the `dl.k8s.io` URL has been introduced.
xref: https://github.com/kubernetes/k8s.io/issues/2396

chore: use `dl.k8s.io` instead of hardcoded url

---

docker/proxy-init.Dockerfile

- update distroless-iptables to `v0.2.5`
- resolves CVEs in `v0.2.4` (xref: https://dev.azure.com/AzureContainerUpstream/Azure%20Workload%20Identity/_build/results?buildId=101037&view=logs&jobId=50e5c204-a982-5a63-4824-cf22f1b24a4e&j=50e5c204-a982-5a63-4824-cf22f1b24a4e&t=94cd4644-8683-57bb-f7f8-715cbe70e34e)

chore: update distroless-iptables to v0.2.5

---

docs/book/src/topics/language-specific-examples/azure-identity-sdk.md

- update minimum required and recommended azidentity sdk versions
fixes https://github.com/Azure/azure-workload-identity/issues/975

docs: update minimum required and recommended azidentity sdk versions

---

README.md
docs/book/src/quick-start.md
docs/book/src/topics/language-specific-examples.md
docs/book/src/troubleshooting.md

```bash
➜ curl -s -o /dev/null -w "%{http_code}" https://azure.microsoft.com/en-us/services/active-directory/
301
➜ curl -s -o /dev/null -w "%{http_code}" https://azure.microsoft.com/en-us/products/active-directory/
200
```
fixes markdown link failure: https://github.com/Azure/azure-workload-identity/actions/runs/5381004949/jobs/9764511553
https://azure.microsoft.com/ seems to be failing here. This might be because of some change in the direct behavior, so temporarily disabling the check for that URL.

docs: fix aad url

---

.github/dependabot.yml

Adding groups for k8s and azure-sdk-for-go deps, so we have a single PR for each (xref: https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/)

ci: add dependabot group for gomod (part 1)

---

.github/dependabot.yml

Adding groups for all deps for a package-ecosystem in `examples/*`, so we have a single PR for each

ci: add dependabot group for `examples/*` dir (part 2)

---

scripts/create-aks-cluster.sh

`v1.24` is no longer supported. The AKS LIST versions has API has changed in a backward incompatible way. It no longer has `orchestrators[*].orchestratorVersion`. Refer to https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/list-kubernetes-versions?tabs=HTTP#kubernetesversionlistresult for sample result.

ci: update kubernetes version to v1.26 for aks

---

docs/book/src/known-issues.md
pkg/webhook/webhook.go
pkg/webhook/webhook_test.go

- disallow injecting proxy sidecar in pods with `hostNetwork: true`
- add a note about it in known issues

fix: disallow injecting proxy sidecar in pods with `hostNetwork: true`

---

pkg/proxy/proxy_test.go

- add unit test for `NewProxy`

test: add unit test for proxy

---

pkg/webhook/webhook.go
pkg/webhook/webhook_test.go

- remove unused error in the function
- add unit tests for webhook handler errors

refactor: remove err return and add unit tests for handle errors 

---

pkg/webhook/webhook.go
pkg/webhook/webhook_test.go

To fix application container startup errors due to incorrect container ordering (proxy sidecar will be triggered last instead of first).
fixes #1101
This PR builds on top of https://github.com/Azure/azure-workload-identity/pull/1102 and fixes the unit tests.

fix: prepend proxy sidecar container to prevent application container restarts

---

docker/proxy-init.Dockerfile

- update distroless-iptables to `v0.4.1`
- resolves base image CVEs: https://dev.azure.com/AzureContainerUpstream/Azure%20Workload%20Identity/_build/results?buildId=131577&view=logs&jobId=50e5c204-a982-5a63-4824-cf22f1b24a4e&j=50e5c204-a982-5a63-4824-cf22f1b24a4e&t=94cd4644-8683-57bb-f7f8-715cbe70e34e

chore: update distroless-iptables to v0.4.1

---

.github/workflows/azwi-build.yaml
.github/workflows/azwi-e2e.yaml
.github/workflows/codecov.yaml
.github/workflows/create-release-pull-request.yaml
.github/workflows/create-release.yaml
.golangci.yml
docker/proxy-init.Dockerfile
docker/proxy.Dockerfile
docker/webhook.Dockerfile
examples/msal-go/Dockerfile
examples/msal-go/windows.Dockerfile
go.mod
go.sum
test/e2e/go.mod
test/e2e/go.sum

- update to go 1.21
- update distroless-iptables image to v1.4.2 to fix CVE-2023-5363

chore: update to go 1.21

---

.github/workflows/azwi-build.yaml
.github/workflows/azwi-e2e.yaml
.github/workflows/codecov.yaml
.github/workflows/create-release-pull-request.yaml
.github/workflows/create-release.yaml

Set `check-latest: true` in gh workflows.
If check-latest is set to true, the action first checks if the cached version is the latest one. If the locally cached version is not the most up-to-date, a Go version will then be downloaded. (xref: https://github.com/actions/setup-go?tab=readme-ov-file#check-latest-version).

ci: set check-latest flag to true in gh workflows

---

docker/proxy-init.Dockerfile
docker/proxy.Dockerfile
docker/webhook.Dockerfile
examples/msal-go/Dockerfile
examples/msal-go/windows.Dockerfile
examples/msal-node/Dockerfile
examples/msal-python/Dockerfile

- use base images from mcr
- bump distroless-iptables to `v0.4.3`

chore: use base images from mcr

---

docs/book/src/installation/self-managed-clusters/oidc-issuer/discovery-document.md
scripts/wi-kind-setup.sh

This PR adds script to setup kind cluster for WI. This script does following:
1. Setup storage account.
2. Configure issuer url in kind config and create cluster.
2.a The issuer url can be determined using the storage account and container name.
2.b Let kubeadm generate the signing keys instead of pre-generating and mounting it.
3. Get the public signing key from the cluster.
4. Generate the JWKS using the public key and upload it to storage account.

feat: adds script to setup OIDC issuer

---

.github/workflows/create-release.yaml

`--rm-dist` is deprecated, using `--clean` instead.

release: update manifest and helm charts for v1.2.1 (part 2)

---

.pipelines/templates/scan-images.yaml
scripts/create-aks-cluster.sh

Remove pinned k8s version for aks clusters in CI.
This will resolve cluster creation failure in CI: https://dev.azure.com/AzureContainerUpstream/Azure%20Workload%20Identity/_build/results?buildId=162979&view=logs&jobId=377f0d06-9179-5249-f9a7-28bb5766ad7b&j=b3c1b3ef-28d7-5409-0106-cc1f1619b84c&t=9e7e4005-272c-58b2-628a-739ad1a735d9

ci: remove pinned k8s version for aks clusters

---

.github/workflows/scan-vulns.yaml

- bump go-version to 1.22 for govulncheck workflow

ci: bump go-version to 1.22 for govulncheck workflow

---

.pipelines/templates/scan-images.yaml
docker/proxy-init.Dockerfile

fixes https://github.com/Azure/azure-workload-identity/issues/1336

chore: update distroless-iptables to v0.5.4

---

docs/book/src/faq.md

The `workload_identity_client_id` parameter of `DefaultAzureCredential` is a better fit for this use case. Update the content accordingly, and conduct an edit pass too.

docs: Update Azure Identity for Python content

---

.pipelines/nightly.yaml
.pipelines/pr.yaml
scripts/create-aks-cluster.sh

- The default container runtime is `containerd` in windows, so the `windows_containerd` job is a duplicate with steps that weren't required.

ci: cleanup windows pr gate

---

docker/proxy-init.Dockerfile

- update distroless-iptables to `v0.6.0`
resolves https://dev.azure.com/AzureContainerUpstream/Azure%20Workload%20Identity/_build/results?buildId=174136&view=logs&jobId=50e5c204-a982-5a63-4824-cf22f1b24a4e&j=50e5c204-a982-5a63-4824-cf22f1b24a4e&t=94cd4644-8683-57bb-f7f8-715cbe70e34e

chore: update distroless-iptables to v0.6.0

---

examples/msal-go/token_credential.go
pkg/proxy/proxy.go

According to the function signature
```go
// New is the constructor for Client. authority is the URL of a token authority such as "https://login.microsoftonline.com/<your tenant>".
// If the Client will connect directly to AD FS, use "adfs" for the tenant. clientID is the application's client ID (also called its
// "application ID").
func New(authority, clientID string, cred Credential, options ...Option) (Client, error) {
```
xref: https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/v1.2.2/apps/confidential/confidential.go#L310-L313

fix: update authority url in confidential client

---

docker/proxy-init.Dockerfile

update distroless-iptables to `v0.6.5`

chore: update distroless-iptables to v0.6.5

---

.github/workflows/create-release.yaml
.goreleaser.yml

```shell
azure-workload-identity on  aramase/ci/goreleaser_v2 [$] 
➜ goreleaser check
• checking                                 path=.goreleaser.yml
• 1 configuration file(s) validated
• thanks for using goreleaser!
```

ci: update goreleaser config for v2

---

.github/workflows/azwi-e2e.yaml

`azwi_e2e` is not being used because it requires an Azure AD App that has owner level permission to a sub for creating/deleting further SPs. Previously this test was using my test sub but that has since been removed.

ci: remove unused azwi_e2e job

---

docs/book/src/topics/self-managed-clusters/service-account-key-rotation.md

```shell
➜ curl -s -o /dev/null -w "%{http_code}" https://jwt.io
500
➜ curl -s -o /dev/null -w "%{http_code}" https://jwt.ms
200
```
fixes `markdown-link-check` workflow failures (ref: https://github.com/Azure/azure-workload-identity/actions/runs/13125108483/job/36619728621)

docs: use jwt.ms link for inspecting token

---

cmd/webhook/main.go
pkg/webhook/webhook.go
pkg/webhook/webhook_test.go
test/e2e/e2e.go
test/e2e/helpers.go
test/e2e/proxy_test.go

Fixes [Issue 773](https://github.com/Azure/azure-workload-identity/issues/773) by using [native sidecars](https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/) so that pods exit cleanly when running as cronjobs, currently azwi sidecar prevents the pod from terminating. 
It also addresses an annoyance where the first container in the pod is the proxy, so any `kubectl` commands target that container, previously I was working around this by adding the [default-container](https://kubernetes.io/docs/reference/labels-annotations-taints/#kubectl-kubernetes-io-default-container) annotation.
When running on kubernetes >=1.28 it will use native sidecars, otherwise it will use the original approach.
No update to deployment.yaml
No change to Helm chart …

feat: allow proxies to be injected using a native sidecar

---

examples/msal-python/requirements.txt
examples/msal-python/token_credential.py

The previous sample was a proof-of-concept which only worked as a one-off script, and inefficiently. Problems include:
* Even if you rerun the script immediately, a new file I/O and new http I/O would incur.
* If a real app changes the previous sample into a long-lived daemon, the federation assertion would soon become outdated because the sample never reloads the assertion.
After this PR, the sample, if being used as a long-lived daemon, will automatically attempt token search from cache, and automatically reload the assertion when cache misses.
No.
No.
Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide …

chore: optimize the Python sample

---

test/e2e/helpers.go
test/e2e/proxy_test.go
test/e2e/token_exchange.go
test/e2e/webhook.go

We don't need any label on the Kubernetes service account (this was the old behavior), so cleaning up those labels in e2e.

test: cleanup use of wi labels in service account for e2e

---

pkg/webhook/webhook.go
pkg/webhook/webhook_test.go

As explained in more details in #1555, results of webhook mutation would be better if empty environment variables are not added to container spec. - `Env` section of a pod spec (used by the webhook) has higher precedence than `envFrom`, so if the environment variables are imported using the latter, container still starts with empty values populated by the webhook.
Fixes: #1555
At first, I proposed to make the change only for `AZURE_CLIENT_ID`, @aramase agreed to that in the related issue: …

fix(webhook): do not add environment variables when they are empty

---

scripts/create-kind-cluster.sh
test/e2e/proxy_test.go

- When `preflight` is true, we don't check for the keys downloaded from AKV. This additional checks also ensures we don't attempt the download the keys when not required.
- Use `--client-id` for az login in the e2e suite as `--username` is no longer supported
```bash
File "/usr/lib64/az/lib/python3.12/site-packages/azure/cli/command_modules/profile/custom.py", line 137, in login
raise CLIError('Passing the managed identity ID with --username is no longer supported. '
knack.util.CLIError: Passing the managed identity ID with --username is no longer supported. Use --client-id, --object-id or --resource-id instead.
```

ci: skip key download if preflight is true

---

.pipelines/nightly.yaml

The deploy manifests are already being validated as part of the e2e suite:
https://github.com/Azure/azure-workload-identity/blob/30e0f1b79f36c41a459bcf5331fe3641e1fab90a/scripts/ci-e2e.sh#L68

ci: rm verify deploy yaml nightly job

---

pkg/config/config.go
pkg/config/config_test.go

Set a default vaue to the token proxy so AKS deployment can use this value immediately.

feat: add fallback for AzureKubernetesTokenProxy
